### ISSUE TITLE
Add typescript types

### ISSUE THREAD

**Issue by shaharmor** [invertase/cluster-key-slot#6]
Hi,

Its difficult to use this module in a TypeScript project as it has no typings available.

Would you consider adding some?

**Comment by Ehesp** [comment]
Hello

Yeah we can add this, however it may take a little bit of time. We'd accept a PR to speed it along.

**Comment by Ehesp** [comment]
Closed via https://github.com/invertase/cluster-key-slot/commit/3aec6fcdcaf2c3ee2b974d5e928215db3af3fbb2
